const data = [
    ['Alternative', 'Alternative Rock'],
    ['Alternative', 'College Rock'],
    ['Alternative', 'Experimental Rock'],
    ['Alternative', 'Goth Rock'],
    ['Alternative', 'Grunge'],
    ['Alternative', 'Hardcore Punk'],
    ['Alternative', 'Hard Rock'],
    ['Alternative', 'Indie Rock'],
    ['Alternative', 'New Wave'],
    ['Alternative', 'Progressive Rock'],
    ['Alternative', 'Punk'],
    ['Alternative', 'Shoegaze'],
    ['Alternative', 'Steampunk'],
    ['Blues','Acoustic Blues'],
    ['Blues','Chicago Blues'],
    ['Blues','Classic Blues'],
    ['Blues','Contemporary Blues'],
    ['Blues','Country Blues'],
    ['Blues','Delta Blues'],
    ['Blues','Electric Blues'],
    ["Children's Music", 'Lullabies'],
    ["Children's Music", 'Sing-Along'],
    ["Children's Music", 'Stories'],
    ['Classical', 'Avant-Garde'],
    ['Classical', 'Baroque'],
    ['Classical', 'Chamber Music'],
    ['Classical', 'Chant'],
    ['Classical', 'Choral'],
    ['Classical', 'Classical Crossover'],
    ['Classical', 'Early Music'],
    ['Classical', 'High Classical'],
    ['Classical', 'Impressionist'],
    ['Classical', 'Medieval'],
    ['Classical', 'Minimalism'],
    ['Classical', 'Modern Composition'],
    ['Classical', 'Opera'],
    ['Classical', 'Orchestral'],
    ['Classical', 'Renaissance'],
    ['Classical', 'Romantic'],
    ['Classical', 'Wedding Music'],
    ['Classical', 'Opera'],
    ['Comedy', 'Novelty'],
    ['Comedy', 'Standup Comedy'],
    ['Country', 'Alternative Country'],
    ['Country', 'Americana'],
    ['Country', 'Bluegrass'],
    ['Country', 'Contemporary Bluegrass'],
    ['Country', 'Contemporary Country'],
    ['Country', 'Country Gospel'],
    ['Country', 'Honky Tonk'],
    ['Country', 'Outlaw Country'],
    ['Country', 'Traditional Bluegrass'],
    ['Country', 'Traditional Country'],
    ['Country', 'Urban Cowboy'],
    ['Dance-EDM', 'Breakbeat'],
    ['Dance-EDM', 'Dubstep'],
    ['Dance-EDM', 'Exercise'],
    ['Dance-EDM', 'Garage'],
    ['Dance-EDM', 'Hardcore'],
    ['Dance-EDM', 'Hard Dance'],
    ['Dance-EDM', 'Hi-NRG / Eurodance'],
    ['Dance-EDM', 'House'],
    ['Dance-EDM', 'Jackin House'],
    ['Dance-EDM', 'Jungle/Drum and bass'],
    ['Dance-EDM', 'Techno'],
    ['Dance-EDM', 'Trance'],
    ["Easy Listening", 'Bop'],
    ["Easy Listening", 'Lounge'],
    ["Easy Listening", 'Swing'],
    ['Electronic', 'Ambient'],
    ['Electronic', 'Crunk'],
    ['Electronic', 'Downtempo'],
    ['Electronic', 'Electro'],
    ['Electronic', 'Electronica'],
    ['Electronic', 'Electronic Rock'],
    ['Electronic', 'IDM/Experimental'],
    ['Electronic', 'Industrial'],
    ['Hip-Hop/Rap', 'Alternative Rap'],
    ['Hip-Hop/Rap', 'Bounce'],
    ['Hip-Hop/Rap', 'Dirty South'],
    ['Hip-Hop/Rap', 'East Coast Rap'],
    ['Hip-Hop/Rap', 'Gangsta Rap'],
    ['Hip-Hop/Rap', 'Hardcore Rap'],
    ['Hip-Hop/Rap', 'Hip-Hop'],
    ['Hip-Hop/Rap', 'Latin Rap'],
    ['Hip-Hop/Rap', 'Old School Rap'],
    ['Hip-Hop/Rap', 'Rap'],
    ['Hip-Hop/Rap', 'Underground Rap'],
    ['Hip-Hop/Rap', 'West Coast Rap'],
    ['Holiday', 'Chanukah'],
    ['Holiday', 'Christmas'],
    ['Holiday', 'Christmas-Children'],
    ['Holiday', 'Christmas-Classic'],
    ['Holiday', 'Christmas-Classical'],
    ['Holiday', 'Christmas-Jazz'],
    ['Holiday', 'Christmas-Modern'],
    ['Holiday', 'Christmas-Pop'],
    ['Holiday', 'Christmas-R&B'],
    ['Holiday', 'Christmas-Religious'],
    ['Holiday', 'Christmas-Rock'],
    ['Holiday', 'Easter'],
    ['Holiday', 'Halloween'],
    ['Holiday', 'Holiday-Other'],
    ['Holiday', 'Thanksgiving'],
    ['Insperational & Gospel', 'CCM'],
    ['Insperational & Gospel', 'Christian Metal'],
    ['Insperational & Gospel', 'Christian Pop'],
    ['Insperational & Gospel', 'Christian Rap'],
    ['Insperational & Gospel', 'Christian Rock'],
    ['Insperational & Gospel', 'Classic Christian'],
    ['Insperational & Gospel', 'Contemporary Gospel'],
    ['Insperational & Gospel', 'Gospel'],
    ['Insperational & Gospel', 'Christian & Gospel'],
    ['Insperational & Gospel', 'Praise & Worship'],
    ['Insperational & Gospel', 'Qawwali'],
    ['Insperational & Gospel', 'Southern Gospel'],
    ['Insperational & Gospel', 'Traditional Gospel'],
    ['J-Pop', 'J-Rock'],
    ['J-Pop', 'J-Synth'],
    ['J-Pop', 'J-Ska'],
    ['J-Pop', 'J-Punk'],
    ['Jazz', 'Acid Jazz'],
    ['Jazz', 'Avant-Garde Jazz'],
    ['Jazz', 'Big Band'],
    ['Jazz', 'Blue Note'],
    ['Jazz', 'Contemporary Jazz'],
    ['Jazz', 'Cool'],
    ['Jazz', 'Crossover Jazz'],
    ['Jazz', 'Dixieland'],
    ['Jazz', 'Ethio-jazz'],
    ['Jazz', 'Fusion'],
    ['Jazz', 'Hard Bop'],
    ['Jazz', 'Latin Jazz'],
    ['Jazz', 'Mainstream Jazz'],
    ['Jazz', 'Ragtime'],
    ['Jazz', 'Smooth Jazz'],
    ['Jazz', 'Trad Jazz'],
    ['Latino', 'Alternativo & Rock Latino'],
    ['Latino', 'Baladas y Boleros'],
    ['Latino', 'Brazilian'],
    ['Latino', 'Contemporary Latin'],
    ['Latino', 'Latin Jazz'],
    ['Latino', 'Pop Latino'],
    ['Latino', 'Raíces'],
    ['Latino', 'Reggaeton y Hip-Hop'],
    ['Latino', 'Regional Mexicano'],
    ['Latino', 'Salsa y Tropical'],
    ['Misc', 'Karaoke'],
    ['Misc', 'Instrumental'],
    ['Misc', 'Fitness & Workout'],
    ['New Age', 'Environmental'],
    ['New Age', 'Healing'],
    ['New Age', 'Meditation'],
    ['New Age', 'Nature'],
    ['New Age', 'Relaxation'],
    ['New Age', 'Travel'],
    ['New Age', 'Industrial'],
    ['Pop', 'Adult Contemporary'],
    ['Pop', 'Britpop'],
    ['Pop', 'Pop-Rock'],
    ['Pop', 'Soft Rock'],
    ['Pop', 'Teen Pop'],
    ['Pop', 'Indie Pop'],
    ['Pop', 'French Pop'],
    ['Pop', 'German Pop'],
    ['Pop', 'K-Pop'],
    ['R&B-Soul', 'Contemporary R&B'],
    ['R&B-Soul', 'Disco'],
    ['R&B-Soul', 'Doo Wop'],
    ['R&B-Soul', 'Funk'],
    ['R&B-Soul', 'Motown'],
    ['R&B-Soul', 'Neo-Soul'],
    ['R&B-Soul', 'Quiet Storm'],
    ['R&B-Soul', 'Soul'],
    ['Reggae', 'Dancehall'],
    ['Reggae', 'Dub'],
    ['Reggae', 'Roots Reggae'],
    ['Reggae', 'Ska'],    
    ['Rock', 'Adult Alternative'],
    ['Rock', 'American Trad Rock'],
    ['Rock', 'Arena Rock'],
    ['Rock', 'Blues-Rock'],
    ['Rock', 'British Invasion'],
    ['Rock', 'Death Metal/Black Metal'],
    ['Rock', 'Glam Rock'],
    ['Rock', 'Hair Metal'],
    ['Rock', 'Hard Rock'],
    ['Rock', 'Metal'],
    ['Rock', 'Jam Bands'],
    ['Rock', 'Prog-Rock/Art Rock'],
    ['Rock', 'Psychedelic'],
    ['Rock', 'Rock & Roll'],
    ['Rock', 'Rockabilly'],
    ['Rock', 'Roots Rock'],
    ['Rock', 'Singer/Songwriter'],
    ['Rock', 'Southern Rock'],
    ['Rock', 'Surf'],
    ['Rock', 'Tex-Mex'],
    ['Singer-Songwriter', 'Alternative Folk'],
    ['Singer-Songwriter', 'Contemporary Folk'],
    ['Singer-Songwriter', 'Contemporary Singer/Songwriter'],
    ['Singer-Songwriter', 'Folk-Rock'],
    ['Singer-Songwriter', 'New Acoustic'],
    ['Singer-Songwriter', 'Traditional Folk'],
    ['Soundtrack', 'Foreign Cinema'],
    ['Soundtrack', 'Musicals'],
    ['Soundtrack', 'Original Score'],
    ['Soundtrack', 'Soundtrack'],
    ['Soundtrack', 'TV Soundtrack'],
    ['Soundtrack', 'Disney'],
    ['Soundtrack', 'Anime'],
    ['Tex Mex-Tejano', 'Chicano'],
    ['Tex Mex-Tejano', 'Classic'],
    ['Tex Mex-Tejano', 'Conjunto'],
    ['Tex Mex-Tejano', 'Conjunto Progressive'],
    ['Tex Mex-Tejano', 'New Mex'],
    ['Tex Mex-Tejano', 'Tex-Mex'],
    ['Vocal', 'Barbershop'],
    ['Vocal', 'Doo-wop'],
    ['Vocal', 'Standards'],
    ['Vocal', 'Traditional Pop'],
    ['Vocal', 'Vocal Jazz'],
    ['Vocal', 'Vocal Pop'],
    ['Vocal', 'Spoken Word'],
    ['World', 'Africa'],
    ['World', 'Afro-Beat'],
    ['World', 'Afro-Pop'],
    ['World', 'Asia'],
    ['World', 'Australia'],
    ['World', 'Bossa Nova'],
    ['World', 'Cajun'],
    ['World', 'Caribbean'],
    ['World', 'Celtic'],
    ['World', 'Celtic Folk'],
    ['World', 'Contemporary Celtic'],
    ['World', 'Drinking Songs'],
    ['World', 'Drone'],
    ['World', 'Europe'],
    ['World', 'France'],
    ['World', 'German Folk'],
    ['World', 'Hawaii'],
    ['World', 'Indian Pop'],
    ['World', 'Japan'],
    ['World', 'Japanese Pop'],
    ['World', 'Klezmer'],
    ['World', 'Kayokyoku'],
    ['World', 'Middle East'],
    ['World', 'North America'],
    ['World', 'Polka'],
    ['World', 'South Africa'],
    ['World', 'South America'],
    ['World', 'Traditional Celtic'],
    ['World', 'Worldbeat'],
    ['World', 'Zydeco']
];


function makeDropDown(data, level1Filter){

    const filteredArray = data.filter(r => r[0] === level1Filter);

    const uniqueList = getUniqueValues(filteredArray, 1);

    const selectLevel2 = document.getElementById("level2");

    populateDropDown(selectLevel2, uniqueList)
}

makeDropDown(data, 'World')

function applyDropDown(){
    const selectLevel1Value = document.getElementById("level1").value;
    makeDropDown(data, selectLevel1Value);
}

function afterDocumentLoads(){
    populateFirstLevelDropDown();
    applyDropDown();
}

function getUniqueValues(data, Index){
    const uniqueOptions = new Set();
    data.forEach(r => uniqueOptions.add(r(index)));
    return [...uniqueOptions];
}

function populateFirstLevelDropDown(){
    const uniqueList = getUniqueValues(data, 0);
    const el = document.getElementById("level1");
    populateDropDown(el, uniqueList)
}

function populateDropDown(el, listAsArray){
    el.innerHTML = "";

    listAsArray.forEach(item => {
        const option = document.createElement("option");
        option.textContent = item;
        el.appendChild(option);
    });
}

document.getElementById("level1").addEventListener("change", applyDropDown);
document.addEventListener('DOMContentLoaded', afterDocumentLoads);





