from os import environ
from model import Genre, Subgenre, User, connect_to_db, db
from flask import Flask


#genre id foreign key and subgenre name
subgenre_data = [
    [1, 'Alternative Rock'],
    [1, 'College Rock'],
    [1, 'Experimental Rock'],
    [1, 'Goth Rock'],
    [1, 'Grunge'],
    [1, 'Hardcore Punk'],
    [1, 'Hard Rock'],
    [1, 'Indie Rock'],
    [1, 'New Wave'],
    [1, 'Progressive Rock'],
    [1, 'Punk'],
    [1, 'Shoegaze'],
    [1, 'Steampunk'],
    [2,'Acoustic Blues'],
    [2,'Chicago Blues'],
    [2,'Classic Blues'],
    [2,'Contemporary Blues'],
    [2,'Country Blues'],
    [2,'Delta Blues'],
    [2,'Electric Blues'],
    [3, 'Lullabies'],
    [3, 'Sing-Along'],
    [3, 'Stories'],
    [4, 'Avant-Garde'],
    [4, 'Baroque'],
    [4, 'Chamber Music'],
    [4, 'Chant'],
    [4, 'Choral'],
    [4, 'Classical Crossover'],
    [4, 'Early Music'],
    [4, 'High Classical'],
    [4, 'Impressionist'],
    [4, 'Medieval'],
    [4, 'Minimalism'],
    [4, 'Modern Composition'],
    [4, 'Opera'],
    [4, 'Orchestral'],
    [4, 'Renaissance'],
    [4, 'Romantic'],
    [4, 'Wedding Music'],
    [4, 'Opera'],
    [5, 'Novelty'],
    [5, 'Standup Comedy'],
    [6, 'Alternative Country'],
    [6, 'Americana'],
    [6, 'Bluegrass'],
    [6, 'Contemporary Bluegrass'],
    [6, 'Contemporary Country'],
    [6, 'Country Gospel'],
    [6, 'Honky Tonk'],
    [6, 'Outlaw Country'],
    [6, 'Traditional Bluegrass'],
    [6, 'Traditional Country'],
    [6, 'Urban Cowboy'],
    [7, 'Breakbeat'],
    [7, 'Dubstep'],
    [7, 'Exercise'],
    [7, 'Garage'],
    [7, 'Hardcore'],
    [7, 'Hard Dance'],
    [7, 'Hi-NRG / Eurodance'],
    [7, 'House'],
    [7, 'Jackin House'],
    [7, 'Jungle/Drum and bass'],
    [7, 'Techno'],
    [7, 'Trance'],
    [8, 'Bop'],
    [8, 'Lounge'],
    [8, 'Swing'],
    [9, 'Ambient'],
    [9, 'Crunk'],
    [9, 'Downtempo'],
    [9, 'Electro'],
    [9, 'Electronica'],
    [9, 'Electronic Rock'],
    [9, 'IDM/Experimental'],
    [9, 'Industrial'],
    [10, 'Alternative Rap'],
    [10, 'Bounce'],
    [10, 'Dirty South'],
    [10, 'East Coast Rap'],
    [10, 'Gangsta Rap'],
    [10, 'Hardcore Rap'],
    [10, 'Hip-Hop'],
    [10, 'Latin Rap'],
    [10, 'Old School Rap'],
    [10, 'Rap'],
    [10, 'Underground Rap'],
    [10, 'West Coast Rap'],
    [11, 'Chanukah'],
    [11, 'Christmas'],
    [11, 'Christmas-Children'],
    [11, 'Christmas-Classic'],
    [11, 'Christmas-Classical'],
    [11, 'Christmas-Jazz'],
    [11, 'Christmas-Modern'],
    [11, 'Christmas-Pop'],
    [11, 'Christmas-R&B'],
    [11, 'Christmas-Religious'],
    [11, 'Christmas-Rock'],
    [11, 'Easter'],
    [11, 'Halloween'],
    [11, 'Holiday-Other'],
    [11, 'Thanksgiving'],
    [12, 'CCM'],
    [12, 'Christian Metal'],
    [12, 'Christian Pop'],
    [12, 'Christian Rap'],
    [12, 'Christian Rock'],
    [12, 'Classic Christian'],
    [12, 'Contemporary Gospel'],
    [12, 'Gospel'],
    [12, 'Christian & Gospel'],
    [12, 'Praise & Worship'],
    [12, 'Qawwali'],
    [12, 'Southern Gospel'],
    [12, 'Traditional Gospel'],
    [13, 'J-Rock'],
    [13, 'J-Synth'],
    [13, 'J-Ska'],
    [13, 'J-Punk'],
    [14, 'Acid Jazz'],
    [14, 'Avant-Garde Jazz'],
    [14, 'Big Band'],
    [14, 'Blue Note'],
    [14, 'Contemporary Jazz'],
    [14, 'Cool'],
    [14, 'Crossover Jazz'],
    [14, 'Dixieland'],
    [14, 'Ethio-jazz'],
    [14, 'Fusion'],
    [14, 'Hard Bop'],
    [14, 'Latin Jazz'],
    [14, 'Mainstream Jazz'],
    [14, 'Ragtime'],
    [14, 'Smooth Jazz'],
    [14, 'Trad Jazz'],
    [15, 'Alternativo & Rock Latino'],
    [15, 'Baladas y Boleros'],
    [15, 'Brazilian'],
    [15, 'Contemporary Latin'],
    [15, 'Latin Jazz'],
    [15, 'Pop Latino'],
    [15, 'Raíces'],
    [15, 'Reggaeton y Hip-Hop'],
    [15, 'Regional Mexicano'],
    [15, 'Salsa y Tropical'],
    [16, 'Karaoke'],
    [16, 'Instrumental'],
    [16, 'Fitness & Workout'],
    [17, 'Environmental'],
    [17, 'Healing'],
    [17, 'Meditation'],
    [17, 'Nature'],
    [17, 'Relaxation'],
    [17, 'Travel'],
    [18, 'Adult Contemporary'],
    [18, 'Britpop'],
    [18, 'Pop-Rock'],
    [18, 'Soft Rock'],
    [18, 'Teen Pop'],
    [18, 'Indie Pop'],
    [18, 'French Pop'],
    [18, 'German Pop'],
    [18, 'K-Pop'],
    [19, 'Contemporary R&B'],
    [19, 'Disco'],
    [19, 'Doo Wop'],
    [19, 'Funk'],
    [19, 'Motown'],
    [19, 'Neo-Soul'],
    [19, 'Quiet Storm'],
    [19, 'Soul'],
    [20, 'Dancehall'],
    [20, 'Dub'],
    [20, 'Roots Reggae'],
    [20, 'Ska'],    
    [21, 'Adult Alternative'],
    [21, 'American Trad Rock'],
    [21, 'Arena Rock'],
    [21, 'Blues-Rock'],
    [21, 'British Invasion'],
    [21, 'Death Metal/Black Metal'],
    [21, 'Glam Rock'],
    [21, 'Hair Metal'],
    [21, 'Hard Rock'],
    [21, 'Metal'],
    [21, 'Jam Bands'],
    [21, 'Prog-Rock/Art Rock'],
    [21, 'Psychedelic'],
    [21, 'Rock & Roll'],
    [21, 'Rockabilly'],
    [21, 'Roots Rock'],
    [21, 'Singer/Songwriter'],
    [21, 'Southern Rock'],
    [21, 'Surf'],
    [21, 'Tex-Mex'],
    [22, 'Alternative Folk'],
    [22, 'Contemporary Folk'],
    [22, 'Contemporary Singer/Songwriter'],
    [22, 'Folk-Rock'],
    [22, 'New Acoustic'],
    [22, 'Traditional Folk'],
    [23, 'Foreign Cinema'],
    [23, 'Musicals'],
    [23, 'Original Score'],
    [23, 'TV Soundtrack'],
    [23, 'Disney'],
    [23, 'Anime'],
    [24, 'Chicano'],
    [24, 'Classic'],
    [24, 'Conjunto'],
    [24, 'Conjunto Progressive'],
    [24, 'New Mex'],
    [24, 'Tex-Mex'],
    [25, 'Barbershop'],
    [25, 'Doo-wop'],
    [25, 'Standards'],
    [25, 'Traditional Pop'],
    [25, 'Vocal Jazz'],
    [25, 'Vocal Pop'],
    [25, 'Spoken Word'],
    [26, 'Africa'],
    [26, 'Afro-Beat'],
    [26, 'Afro-Pop'],
    [26, 'Asia'],
    [26, 'Australia'],
    [26, 'Bossa Nova'],
    [26, 'Cajun'],
    [26, 'Caribbean'],
    [26, 'Celtic'],
    [26, 'Celtic Folk'],
    [26, 'Contemporary Celtic'],
    [26, 'Drinking Songs'],
    [26, 'Drone'],
    [26, 'Europe'],
    [26, 'France'],
    [26, 'German Folk'],
    [26, 'Hawaii'],
    [26, 'Indian Pop'],
    [26, 'Japan'],
    [26, 'Japanese Pop'],
    [26, 'Klezmer'],
    [26, 'Kayokyoku'],
    [26, 'Middle East'],
    [26, 'North America'],
    [26, 'Polka'],
    [26, 'South Africa'],
    [26, 'South America'],
    [26, 'Traditional Celtic'],
    [26, 'Worldbeat'],
    [26, 'Zydeco']
];

#Genre names
genre_data = ['Alternative', 'Blues', "Children's Music", 'Classical', 'Comedy', 'Country', 'Dance-EMD', 'Easy Listening', 'Electronic', 'Hip-Hop/Rap', 'Holiday', 'Inspirational-Christian & Gospel', 'J-Pop', 'Jazz', 'Latino', 'Misc', 'New Age', 'Pop', 'R&B-Soul', 'Reggae', 'Rock', 'Singer-Songwriter', 'Soundtrack', 'Tex Mex-Tejano', 'Vocal', 'World']


#seeds genres
def load_genres():
    
    Genre.query.delete()

    for i in genre_data:

        genre = Genre(i)

        db.session.add(genre)
    
    db.session.commit()

#seeds subgenres
def load_subgenres():
    """load subgenres"""

    for list in subgenre_data:
        
        genre_id = list[0]
        sub_genre = list[1]

        subgenre = Subgenre(genre_id=genre_id, sub_genre=sub_genre)

        db.session.add(subgenre)

    db.session.commit()

#seeds admin user
def load_master_user():

    master_user = User("Adminethan", "example@gmail.com", "abc123")

    db.session.add(master_user)

    db.session.commit()


if __name__ == "__main__":
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = environ['URI']
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    connect_to_db(app)

    load_genres()
    load_subgenres()
    load_master_user()