"""initial migration

Revision ID: 75814df4a285
Revises: 
Create Date: 2022-08-09 13:56:02.778594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75814df4a285'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subgenres')
    op.drop_table('posts')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('events')
    op.drop_table('genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genre_id', sa.INTEGER(), server_default=sa.text("nextval('genres_genre_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('genre_id', name='genres_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('events',
    sa.Column('event_id', sa.INTEGER(), server_default=sa.text("nextval('events_event_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('artist', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], name='events_genre_id_fkey'),
    sa.ForeignKeyConstraint(['sub_genre_id'], ['subgenres.sub_genre_id'], name='events_sub_genre_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='events_user_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', name='events_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('posts',
    sa.Column('post_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('post_caption', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name='posts_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='posts_user_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', name='posts_pkey')
    )
    op.create_table('subgenres',
    sa.Column('sub_genre_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_genre', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], name='subgenres_genre_id_fkey'),
    sa.PrimaryKeyConstraint('sub_genre_id', name='subgenres_pkey')
    )
    # ### end Alembic commands ###
